# Generated by Django 3.2.2 on 2021-05-23 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
