# Generated by Django 3.2.2 on 2021-05-23 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_career_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='video',
            field=models.CharField(default=django.utils.timezone.now, max_length=999),
            preserve_default=False,
        ),
    ]
