# Generated by Django 3.2.2 on 2021-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_career_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='video',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
